vich_uploader:
    db_driver: orm

    mappings:
        project_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true 
            namer: vich_uploader.namer_origname

